apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-ml
  template:
    metadata:
      name: fastapi-ml
      labels:
        app: fastapi-ml
    spec:
      containers:
      - name: fastapi-ml
        image: mrgsv/online_inference:v2
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
          limits:
            memory: "10Gi"
            cpu: "500m"
        ports:
          - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 35
          periodSeconds: 5